title: Manzi Portfolio
email: manzimugisa9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a certified expert in Digital & Web Design helping busy people like you generate more leads.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sublimeprince9.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
highlighter: rouge
