title: Manzi Mugisa 
logo: /assets/img/logo.png
description: This is the culmination of my work or work I have happened to collaborate on with companies, individuals and organisations.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
